[package]
name = "cosmonaut-common"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true
description.workspace = true

[dependencies]
bnum = { version = "0.9.0", features = ["numtraits", "nightly", "rand"] }